BANK_PREFIX = "21101998"
USERS_DATA_PATH = "users_data.json"
MESSAGES_DATA_PATH = "messages_data.json"
FAILED_ATTEMPT = 5
AUTHENTICATION_CHOICES = {"1", "2", "3"}
USER_SERVICES_CHOICES = {"1", "2", "3", "4", "5", "6", "7"}
USER_UPDATE_INFORMATION_CHOICES = {"1", "2", "3", "4", "5", "6", "7"}
USER_TRANSACTION_CHOICES = {"1", "2", "3", "4"}
GENDER_SET_CHOICE = {"1": "male", "2": "female", "3": "others"}
SALT_LEN = 12
FIRST_NAME_MAX_LEN =256
MIDDLE_NAME_MAX_LEN = 128
LAST_NAME_MAX_LEN = 128
NOT_ALLOW_NAME_CHARACTER = """`1234567890-=~!@#$%^&*()_+[]\;',./{}|:"<>?"""
PHONE_NUMBER_LEN = 10
MIN_PASSWORD_LEN = 8
MAX_PASSWORD_LEN = 100
ACCOUNT_NUMBER_LEN = 8
SPECIAL_CHARACTERS = """(~!@#$%^&*_-+=`|(){}[]:;"'<>,.?/)"""